// ==========================================
// ESCAPING, FORMATTERS & RICH MEDIA EMBEDS
// ==========================================

// ---------- XSS DEFENCE ----------
// Everything a student can type — display names, usernames, event
// titles, places, descriptions, messages — must pass through one of
// these before it is concatenated into an innerHTML string.

/** Escape text destined for HTML body content. */
export function escapeHtml(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Escape a value that will sit inside a JS string literal in an inline
 * handler, e.g. onclick="doThing('...')".
 *
 * Prefer passing an id (a uid or a Firestore document id) instead of
 * user text — ids are generated by Firebase and are alphanumeric, so
 * they cannot break out of a quoted attribute at all.
 */
export function escapeJsString(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/"/g, "&quot;")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "")
    .replace(/</g, "\\u003C")
    .replace(/>/g, "\\u003E");
}

/**
 * Allow only ids that look like Firebase uids / document ids.
 * Used as a belt-and-braces guard on anything interpolated into markup.
 */
export function safeId(value) {
  const s = String(value || "");
  return /^[A-Za-z0-9_-]{1,128}$/.test(s) ? s : "";
}

// ---------- AVATARS ----------
export function renderAvatar(avatarCode) {
  if (!avatarCode) return "\u{1F464}";
  const code = String(avatarCode);

  // Only https image URLs are allowed. This blocks javascript:, data:
  // and other schemes someone could store in their avatar field.
  if (/^https:\/\//i.test(code)) {
    return `<img src="${escapeHtml(code)}" referrerpolicy="no-referrer" alt="" style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover; display: block;">`;
  }

  // Emoji or short text avatar — escaped, and length-capped so a long
  // string can't be used to break the layout.
  return escapeHtml(code.slice(0, 8));
}

// ---------- TIME ----------
export function formatTime(ms) {
  const messageDate = new Date(ms);
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  const timeString = messageDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  if (messageDate.toDateString() === today.toDateString()) return `Today at ${timeString}`;
  if (messageDate.toDateString() === yesterday.toDateString()) return `Yesterday at ${timeString}`;
  return `${messageDate.toLocaleDateString([], { month: "short", day: "numeric" })} at ${timeString}`;
}

// ---------- MESSAGE BODIES ----------
function decodeEntities(escaped) {
  // Turn an escaped URL back into a real one for use in href/src.
  return escaped
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');
}

function youTubeId(rawUrl) {
  try {
    const u = new URL(rawUrl);
    const host = u.hostname.replace(/^www\./, "");
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || "";
    if (host === "youtube.com" || host === "m.youtube.com") return u.searchParams.get("v") || "";
    return "";
  } catch (e) {
    return "";
  }
}

function spotifyEmbed(rawUrl) {
  try {
    const u = new URL(rawUrl);
    if (u.hostname.replace(/^www\./, "") !== "open.spotify.com") return "";
    if (!/^\/(track|playlist|album)\/[A-Za-z0-9]+$/.test(u.pathname)) return "";
    return `https://open.spotify.com/embed${u.pathname}`;
  } catch (e) {
    return "";
  }
}

export function formatMessage(text, isMediaOnly = false) {
  // Escape FIRST. Everything after this point works on safe text.
  const safeText = escapeHtml(text);
  const urlRegex = /(https?:\/\/[^\s<]+)/g;

  return safeText.replace(urlRegex, function (escapedUrl) {
    const rawUrl = decodeEntities(escapedUrl);
    const margin = isMediaOnly ? "0" : "8px";
    const lead = isMediaOnly ? "" : "<br>";

    // ---- YouTube ----
    const videoId = youTubeId(rawUrl);
    if (/^[A-Za-z0-9_-]{6,20}$/.test(videoId)) {
      return `${lead}
        <div style="margin-top: ${margin}; width: 100%; max-width: 280px; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.15); background: #18181b; position: relative; min-height: 160px;">
          <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: #ff0000; font-size: 36px; z-index: 1;">
            <i class='bx bxl-youtube bx-flashing'></i>
          </div>
          <iframe width="100%" height="160" src="https://www.youtube.com/embed/${videoId}" frameborder="0" style="display: block; position: relative; z-index: 2;" allowfullscreen></iframe>
        </div>`;
    }

    // ---- Spotify ----
    const embedUrl = spotifyEmbed(rawUrl);
    if (embedUrl) {
      return `${lead}
        <div style="margin-top: ${margin}; width: 100%; max-width: 280px; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.15); background: #121212; position: relative; min-height: 152px;">
          <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: #1ed760; font-size: 32px; z-index: 1;">
            <i class='bx bxl-spotify bx-flashing'></i>
          </div>
          <iframe src="${escapeHtml(embedUrl)}" width="100%" height="152" frameborder="0" style="display: block; position: relative; z-index: 2;" allowfullscreen="" allow="clipboard-write; encrypted-media; picture-in-picture" loading="lazy"></iframe>
        </div>`;
    }

    // ---- Plain link (http/https only, already escaped) ----
    return `<a href="${escapedUrl}" target="_blank" rel="noopener noreferrer nofollow" style="color: inherit; font-weight: 700; text-decoration: underline; word-break: break-all;">${escapedUrl}</a>`;
  });
}
