// ==========================================
// ESCAPING, FORMATTERS & RICH MEDIA EMBEDS
// ==========================================

import { eventIdFromUrl } from '../services/shareRules.js';

// ---------- XSS DEFENCE ----------
// Everything a student can type — display names, usernames, event
// titles, places, descriptions, messages — must pass through one of
// these before it is concatenated into an innerHTML string.

/** Escape text destined for HTML body content. */
export function escapeHtml(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Escape a value that will sit inside a JS string literal in an inline
 * handler, e.g. onclick="doThing('...')".
 *
 * Prefer passing an id (a uid or a Firestore document id) instead of
 * user text — ids are generated by Firebase and are alphanumeric, so
 * they cannot break out of a quoted attribute at all.
 */
export function escapeJsString(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/"/g, "&quot;")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "")
    .replace(/</g, "\\u003C")
    .replace(/>/g, "\\u003E");
}

/**
 * Allow only ids that look like Firebase uids / document ids.
 * Used as a belt-and-braces guard on anything interpolated into markup.
 */
export function safeId(value) {
  const s = String(value || "");
  return /^[A-Za-z0-9_-]{1,128}$/.test(s) ? s : "";
}

// ---------- AVATARS ----------
export function renderAvatar(avatarCode) {
  if (!avatarCode) return "\u{1F464}";
  const code = String(avatarCode);

  // Only https image URLs are allowed. This blocks javascript:, data:
  // and other schemes someone could store in their avatar field.
  if (/^https:\/\//i.test(code)) {
    return `<img src="${escapeHtml(code)}" referrerpolicy="no-referrer" alt="" style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover; display: block;">`;
  }

  // Emoji or short text avatar — escaped, and length-capped so a long
  // string can't be used to break the layout.
  return escapeHtml(code.slice(0, 8));
}

// ---------- TIME ----------

/**
 * Milliseconds out of whatever a stamp happens to be.
 *
 * A message now carries two: `time`, the client's own number, which is
 * what the thread is ordered by and what survives being written
 * offline; and `sentAt`, a real server Timestamp, which is what
 * anything that must not be gameable is measured against. Firestore
 * hands the second one back as a Timestamp object, and while the write
 * is still in flight the local copy is a plain number — so everything
 * that reads a stamp goes through here rather than assuming.
 */
export function msOf(value) {
  if (value === null || value === undefined) return 0;
  if (typeof value === "number") return value;
  if (typeof value.toMillis === "function") return value.toMillis();
  if (typeof value.seconds === "number") {
    return value.seconds * 1000 + Math.floor((value.nanoseconds || 0) / 1e6);
  }
  if (value instanceof Date) return value.getTime();
  return 0;
}

export function formatTime(value) {
  const messageDate = new Date(msOf(value));
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  const timeString = messageDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  if (messageDate.toDateString() === today.toDateString()) return `Today at ${timeString}`;
  if (messageDate.toDateString() === yesterday.toDateString()) return `Yesterday at ${timeString}`;
  return `${messageDate.toLocaleDateString([], { month: "short", day: "numeric" })} at ${timeString}`;
}

// ---------- MESSAGE BODIES ----------
function decodeEntities(escaped) {
  // Turn an escaped URL back into a real one for use in href/src.
  return escaped
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');
}

function youTubeId(rawUrl) {
  try {
    const u = new URL(rawUrl);
    const host = u.hostname.replace(/^www\./, "");
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || "";
    if (host === "youtube.com" || host === "m.youtube.com") return u.searchParams.get("v") || "";
    return "";
  } catch (e) {
    return "";
  }
}

function spotifyEmbed(rawUrl) {
  try {
    const u = new URL(rawUrl);
    if (u.hostname.replace(/^www\./, "") !== "open.spotify.com") return "";
    if (!/^\/(track|playlist|album)\/[A-Za-z0-9]+$/.test(u.pathname)) return "";
    return `https://open.spotify.com/embed${u.pathname}`;
  } catch (e) {
    return "";
  }
}

/**
 * A link to one of our own events becomes a CARD in the thread, not a
 * blue URL — the same idea as the YouTube and Spotify embeds below,
 * pointed at ourselves.
 *
 * It renders EMPTY and is filled in afterwards by chatService, because
 * this function is synchronous and the viewer may never have seen the
 * event: filling it needs a read. The placeholder carries the id and
 * nothing else, so the markup is identical whoever is looking, which
 * keeps the message diffing honest.
 *
 * Only our own host, checked in shareRules.isOurHost — a lookalike
 * domain must not be able to dress itself up as an event card in
 * somebody's chat.
 */
function eventEmbed(eventId, rawUrl) {
  return `
    <a class="event-embed" href="${escapeHtml(rawUrl)}"
       data-event-embed="${escapeHtml(eventId)}"
       onclick="return window.openSharedEvent('${escapeHtml(eventId)}', event)">
      <span class="event-embed-body">
        <span class="event-embed-tag"></span>
        <span class="event-embed-title">Opening\u2026</span>
        <span class="event-embed-meta"></span>
      </span>
      <span class="event-embed-go">View</span>
    </a>`;
}

export function formatMessage(text, isMediaOnly = false) {
  // Escape FIRST. Everything after this point works on safe text.
  const safeText = escapeHtml(text);
  const urlRegex = /(https?:\/\/[^\s<]+)/g;

  return safeText.replace(urlRegex, function (escapedUrl) {
    const rawUrl = decodeEntities(escapedUrl);
    // An embed that IS the message needs no gap above it; one that
    // follows text does.
    const spaced = isMediaOnly ? "" : " spaced";
    const lead = isMediaOnly ? "" : "<br>";

    // ---- One of ours ----
    const eventId = eventIdFromUrl(rawUrl);
    if (eventId) return `${lead}${eventEmbed(eventId, rawUrl)}`;

    // ---- YouTube ----
    const videoId = youTubeId(rawUrl);
    if (/^[A-Za-z0-9_-]{6,20}$/.test(videoId)) {
      return `${lead}
        <div class="media-embed yt${spaced}">
          <i class='bx bxl-youtube bx-flashing' aria-hidden="true"></i>
          <iframe src="https://www.youtube.com/embed/${videoId}" title="YouTube"
                  scrolling="no" frameborder="0" loading="lazy" allowfullscreen></iframe>
        </div>`;
    }

    // ---- Spotify ----
    const embedUrl = spotifyEmbed(rawUrl);
    if (embedUrl) {
      return `${lead}
        <div class="media-embed sp${spaced}">
          <i class='bx bxl-spotify bx-flashing' aria-hidden="true"></i>
          <iframe src="${escapeHtml(embedUrl)}" title="Spotify"
                  scrolling="no" frameborder="0" loading="lazy" allowfullscreen=""
                  allow="clipboard-write; encrypted-media; picture-in-picture"></iframe>
        </div>`;
    }

    // ---- Plain link (http/https only, already escaped) ----
    return `<a href="${escapedUrl}" target="_blank" rel="noopener noreferrer nofollow" style="color: inherit; font-weight: 700; text-decoration: underline; word-break: break-all;">${escapedUrl}</a>`;
  });
}
